#include "jmaths_declarations.hpp"
#include "jmaths_constants_and_types.hpp"
#include "jmaths_N.hpp"
#include "jmaths_sign_type.hpp"
#include "jmaths_Z.hpp"
#include "jmaths_Q.hpp"
#include "jmaths_calc.hpp"
#include "jmaths_hash.hpp"
#include "jmaths_literals.hpp"
#include "jmaths_error.hpp"

#include "jmaths_tmpl_N.hpp"
#include "jmaths_tmpl_Z.hpp"
#include "jmaths_tmpl_Q.hpp"
#include "jmaths_tmpl_sign_type.hpp"
